### PR TITLE
Bump pax logging version to clear log4shell vulnerability

### PR DESCRIPTION
**Pull request by AlexanderPico**
Please consider this PR as soon as possible and upload a new version or your app to the Cytoscape App Store.

### CODE REVIEW

**Comment by AlexanderPico** [comment]
Oh, hi @hadfield! :D  Thanks for the merge. Will you be able to build a new jar for this app and upload it to the Cytoscape App Store?

**Comment by hadfield** [comment]
i uploaded a new jar in the app store (and deleted the old one).

**Comment by AlexanderPico** [comment]
Perfect. Many thanks!

**Comment by hadfield** [comment]
👍

**Pull request merged**
